import { Section, SectionHeading } from './Section.jsx'
import Reveal from './Reveal.jsx'

// Compliance trust band. Distinct badge images per standard, generated by
// scripts/gen-compliance.mjs (original artwork, not the trademarked logos).
const badges = [
  { acr: 'GDPR', key: 'gdpr', name: 'General Data Protection Regulation' },
  { acr: 'CCPA', key: 'ccpa', name: 'California Consumer Privacy Act' },
  { acr: 'CASL', key: 'casl', name: "Canada's Anti-Spam Legislation" },
  { acr: 'ACMA', key: 'acma', name: 'Australian Comms & Media Authority' },
  { acr: 'EDPB', key: 'edpb', name: 'European Data Protection Board' },
  { acr: 'CAN-SPAM', key: 'canspam', name: 'US CAN-SPAM Act' },
]

export default function ComplianceBadges({ tone = 'cream' }) {
  return (
    <Section tone={tone}>
      <SectionHeading
        serif
        eyebrowStyle="rule"
        eyebrow="Trust & compliance"
        title="Our compliance"
        description="We operate within the privacy and anti-spam regulations that matter to B2B teams worldwide, so the data you receive is sourced, stored and delivered to a standard you can defend."
      />

      <div className="mt-12 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">
        {badges.map((b, i) => (
          <Reveal key={b.acr} delay={(i % 6) * 0.05}>
            <div className="group flex h-full flex-col items-center rounded-2xl border border-cream-deep bg-card p-5 text-center shadow-soft transition hover:-translate-y-1 hover:shadow-lift">
              <img
                src={`/compliance/${b.key}.png`}
                alt={`${b.acr} compliant`}
                width="64"
                height="79"
                loading="lazy"
                className="h-[4.5rem] w-auto drop-shadow-[0_4px_12px_rgba(0,0,0,0.25)] transition-transform duration-300 group-hover:-translate-y-0.5"
              />
              <div className="mt-3 text-sm font-extrabold tracking-tight text-coal">{b.acr}</div>
              <div className="mt-0.5 text-[0.6rem] font-bold uppercase tracking-[0.16em] text-terracotta">Compliant</div>
              <div className="mt-2 text-[0.7rem] leading-snug text-coal/60">{b.name}</div>
            </div>
          </Reveal>
        ))}
      </div>
    </Section>
  )
}
